services:
  cosmo-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosmo-web
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/ping"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - README.md