services:
  cosmo-web:
    image: ghcr.io/alexraskin/cosmo-web:${GIT_COMMIT_HASH:-latest}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.cosmo-web-https.rule=Host(`cosmothecat.net`) || Host(`www.cosmothecat.net`)"
        - "traefik.http.routers.cosmo-web-https.entrypoints=https"
        - "traefik.http.routers.cosmo-web-https.tls=true"
        - "traefik.http.routers.cosmo-web-https.tls.certresolver=le"
        - "traefik.http.routers.cosmo-web-https.middlewares=cosmo-web-non-www-to-www"
        - "traefik.http.middlewares.cosmo-web-non-www-to-www.redirectregex.regex=^https?://cosmothecat\\.net(.*)"
        - "traefik.http.middlewares.cosmo-web-non-www-to-www.redirectregex.replacement=https://www.cosmothecat.net$${1}"
        - "traefik.http.middlewares.cosmo-web-non-www-to-www.redirectregex.permanent=true"
        - "traefik.http.services.cosmo-web-https.loadbalancer.server.port=5000"

      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
        monitor: 10s
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  traefik-public:
    external: true